import {
  FaGithub,
  FaFigma,
  FaAmazon,
  FaApple,
  FaBandcamp,
  FaBehance,
  FaDiscord,
  FaDribbble,
  FaEtsy,
  FaFacebook,
  FaFacebookMessenger,
  FaGitlab,
  FaGoogleDrive,
  FaGooglePay,
  FaGooglePlay,
  FaInstagram,
  FaKickstarter,
  FaLine,
  FaLinkedin,
  FaMailchimp,
  FaMastodon,
  FaMedium,
  FaMicrosoft,
  FaPatreon,
  FaPaypal,
  FaPinterest,
  FaProductHunt,
  FaReddit,
  FaSignal,
  FaSlack,
  FaSnapchat,
  FaSpotify,
  FaStackOverflow,
  FaSteam,
  FaTelegram,
  FaTiktok,
  FaTrello,
  FaTumblr,
  FaTwitch,
  FaUnsplash,
  FaVimeo,
  FaWhatsapp,
  FaWordpress,
  FaYoutube,
  FaBlog,
  FaCalendarAlt,
  FaDownload,
  FaCode,
  FaEnvelope,
  FaMapMarkerAlt,
  FaPhone,
  FaCommentAlt,
  FaComment,
  FaGlobe,
} from "react-icons/fa";
import {
  SiVercel,
  SiNetlify,
  SiAwsamplify,
  SiBuymeacoffee,
  SiAmazonmusic,
  SiApplemusic,
  SiApplepodcasts,
  SiCalendly,
  SiCashapp,
  SiDevdotto,
  SiDiscogs,
  SiFiverr,
  SiGofundme,
  SiGoodreads,
  SiKofi,
  SiNotion,
  SiOnlyfans,
  SiReaddotcv,
  SiRedbubble,
  SiRevolut,
  SiTrakt,
  SiZoom,
} from "react-icons/si";
import {
  FaApplePay,
  FaBluesky,
  FaGoogleScholar,
  FaHashnode,
  FaLetterboxd,
  FaShop,
  FaThreads,
  FaUpwork,
  FaXTwitter,
} from "react-icons/fa6";
import { TbBrandAzure } from "react-icons/tb";

const AllLink = [
  {
    name: "Github",
    icon: FaGithub,
    className: "bg-black text-white border-white border-2",
    arweave: ["5TCycDvnKdGipPGZYHwKqZ8OZvxrRCXIG606L-oaHwc"],
  },
  {
    name: "Vercel",
    icon: SiVercel,
    className: "bg-blue-600 text-white",
    arweave: ["tNb-aJ06qRRcvaEM9M9d6xmO6wJ1gN25WEwRX-eoYd4"],
  },
  {
    name: "Netlify",
    icon: SiNetlify,
    className: "bg-white text-black border-2 border-black",
    arweave: ["L9O1fODEHvBRpw6kktO5PZNM_LwWJh3YgRQdvqQqPTE"],
  },
  {
    name: "AWS Amplify",
    icon: SiAwsamplify,
    className: "bg-white text-black border-2 border-black",
    arweave: ["zldFYjKqAukLkc3-h-FtCjttjBjs21e8sxufq_qbfIU"],
  },
  {
    name: "Figma",
    icon: FaFigma,
    className: "bg-white text-black border-2 border-black",
    arweave: ["0_QVjvhiA8DD4H73aPcDUspZDzNBotynqAgtEtAoUXE"],
  },
  {
    name: "Buy me a Coffee",
    icon: SiBuymeacoffee,
    className: "bg-[#ffdd00] border-2 border-black text-black",
    arweave: ["ewYtlYJD9K-8ErmimKFZsuEJ3lqiOklPezHne9AHmF4"],
  },
  {
    name: "Amazon",
    icon: FaAmazon,
    className: "bg-white text-black border-2 border-black",
    arweave: ["Zx9wwsTkz3ZUqtSsZ6s6OtHsQvDqOq0b3cWROBrvpM4"],
  },
  {
    name: "Amazon Music",
    icon: SiAmazonmusic,
    className: "bg-white text-black border-2 border-black",
    arweave: ["YeNFTvhRoihzGPGplUA7hs3l22ObG-prdqt6pJVGdzo"],
  },
  {
    name: "Apple",
    icon: FaApple,
    className: "bg-black text-white border-white border-2",
    arweave: ["P8AnKPRIaxxi6FlfSGJZB6B7BCCH9OnJPQpBjOs_aek"],
  },
  {
    name: "Apple Music",
    icon: SiApplemusic,
    className: "bg-[#FA243C] text-black border-2 border-black",
    arweave: ["H_EPJlL6sGnPdu3-PQpcNMqcKabIWQTZIt9Bh5tEEK8"],
  },
  {
    name: "Apple Podcasts",
    icon: SiApplepodcasts,
    className: "bg-[#9933CC] text-black border-2 border-black",
    arweave: ["boAcsGzs0zeMONt2YHmPAoWwDo2JopPvHYeSnKlJVSc"],
  },
  {
    name: "Apple Pay",
    icon: FaApplePay,
    className: "bg-white text-black border-2 border-black",
    arweave: ["sMH_sWpFT2OUAic4d3O5JjLOsmhOjODjtsglrQPulxw"],
  },
  {
    name: "Bandcamp",
    icon: FaBandcamp,
    className: "bg-sky-500 text-white",
    arweave: ["Nx6egVl5LBf8SjTTfqV8lVzj2KRlfidPSKHbVel0NS4"],
  },
  {
    name: "Behance",
    icon: FaBehance,
    className: "bg-blue-600 text-white",
    arweave: ["uXiMnzaiXMhtypxDddvQNslpS5JTY0nItOJuVn4Ldn8"],
  },
  {
    name: "Bluesky",
    icon: FaBluesky,
    className: "bg-white text-black border-2 border-black",
    arweave: ["OYD12ba2VumccDAqwv02IHGf2v3QXDDU82tfLqhGipY"],
  },
  {
    name: "Calendly",
    icon: SiCalendly,
    className: "bg-blue-500 text-white",
    arweave: ["WdS395Sn7LxTe3QqV5-9iOIN697cRyI86InWZDsBvLc"],
  },
  {
    name: "Cash App",
    icon: SiCashapp,
    className: "bg-white text-black border-2 border-black",
    arweave: ["C7qCKyPW2IFKUB9WJCelg1gtfrs_c9Abh1KwfZWjurI"],
  },
  {
    name: "Dev.to",
    icon: SiDevdotto,
    className: "bg-white text-black border-2 border-black",
    arweave: ["NtwKnIVZXlwyN0-x8V95pOAi4uimbe3byB_fDCQxCZI"],
  },
  {
    name: "Discogs",
    icon: SiDiscogs,
    className: "bg-white text-black border-2 border-black",
    arweave: ["a19hxL9obHMX0SOZ2mVCcgbBKKtcRc2xqhWiyWZwaZk"],
  },
  {
    name: "Discord",
    icon: FaDiscord,
    className: "bg-blue-800 text-white",
    arweave: ["q45Lq8Uy6YWThHz8dn2i01JbU-8-NkMuUa2nxc3IHKo"],
  },
  {
    name: "Dribbble",
    icon: FaDribbble,
    className: "bg-white text-black border-2 border-black",
    arweave: ["5dpisV65wkmA6HCadHVYMpTx086wjBL-6U8MLkS1NdA"],
  },
  {
    name: "Etsy",
    icon: FaEtsy,
    className: "bg-orange-500 text-white",
    arweave: ["PJD76W7PJ2-wVE5jyQRzvnzlAErX4NZE-eeZNZNPAZM"],
  },
  {
    name: "Facebook",
    icon: FaFacebook,
    className: "bg-blue-600 text-white",
    arweave: ["0beAZ0F91VbzmSQUclS5LqW4TZVI_X20wfPJ3jV1nmw"],
  },
  {
    name: "Messenger",
    icon: FaFacebookMessenger,
    className: "bg-blue-600 text-white",
    arweave: ["qTZOu-rY7VLVVVOIgRonGBN_7SN5LzdaGjBHvwfN_Qg"],
  },
  {
    name: "Fiverr",
    icon: SiFiverr,
    className: "bg-emerald-500 text-white",
    arweave: ["DIq3H3gehY738aWhZ_Y6WWxFHP2vYeeoqDbSdiwWh8c"],
  },
  {
    name: "Gitlab",
    icon: FaGitlab,
    className: "bg-indigo-600 text-white",
    arweave: ["boMl5wH5S454UY02sMi3_Ldk5nneIV5NTc8X2MEy7eg"],
  },
  {
    name: "GoFundMe",
    icon: SiGofundme,
    className: "bg-emerald-600 text-white",
    arweave: ["d8I1GmF41L7vhCMwrkhmWaTaJNVZa75Mq8FpZGaWMrc"],
  },
  {
    name: "Goodreads",
    icon: SiGoodreads,
    className: "bg-white text-black border-2 border-black",
    arweave: ["MJIv6yI-V5vIjZpQ7r5uoKNZ4ehu6DZFow0vVZwfNC8"],
  },
  {
    name: "Google Drive",
    icon: FaGoogleDrive,
    className: "bg-black text-white border-white border-2",
    arweave: ["ayx2whiA6UkOB9BBoZseXnVPJx2sTg7vpkgw3IFqTcQ"],
  },
  {
    name: "Google Pay",
    icon: FaGooglePay,
    className: "bg-white text-black border-2 border-black",
    arweave: ["_ONZm8N4gd8eqba_4vRzxB-0Yz-holvvuXbMEc7R950"],
  },
  {
    name: "PlayStore",
    icon: FaGooglePlay,
    className: "bg-black text-white border-white border-2",
    arweave: ["TFfuQnN9ahxPpehN_6T1BqUT_F577A8rVUeESJ86WgI"],
  },
  {
    name: "Google Scholar",
    icon: FaGoogleScholar,
    className: "bg-white text-black border-black border-2",
    arweave: ["DjKujgQsOIXf6l9ZOP_m9a2ADupgtSzaW2U4xwzQMe0"],
  },
  {
    name: "Hashnode",
    icon: FaHashnode,
    className: "bg-white text-black border-black border-2",
    arweave: ["_m8xX2M5y-Ga3gB6BLNuQieCsqjP_eca_uWLNGhlaTM"],
  },
  {
    name: "Instagram",
    icon: FaInstagram,
    className: "bg-pink-600 text-white",
    arweave: ["H28v_t8dqGd7WG7eYGBKiael37M_O9rWEgb7OpMKlIE"],
  },
  {
    name: "Kick",
    icon: FaKickstarter,
    className: "bg-black text-white border-white border-2",
    arweave: ["r0w8MpobxaYljyY1LKSD-sA7pnKJfhyrgGYh_iYKtVA"],
  },
  {
    name: "ko-fi",
    icon: SiKofi,
    className: "bg-sky-400 text-white",
    arweave: ["rexrFYXqruos9QGF_1xvTMXfSgi1MTJHw6C2JF-AuJ8"],
  },
  {
    name: "Letterboxd",
    icon: FaLetterboxd,
    className: "bg-gray-800 text-white border-2 border-white",
    arweave: ["IA19EhDOxG_ik3039V82r80xAluzQD4aXgNPu9-d1eE"],
  },
  {
    name: "Line",
    icon: FaLine,
    className: "bg-green-500 text-white",
    arweave: ["X8k0ehNA-J3EUedRceRTwKLeFGzCeUlpqHrV9vp-hds"],
  },
  {
    name: "Linkedin",
    icon: FaLinkedin,
    className: "bg-blue-700 text-white",
    arweave: ["5Mp4S4GF8HmoObv8V-Z7eMAtBNCo5b74AOJMWhzFsTE"],
  },
  {
    name: "MailChimp",
    icon: FaMailchimp,
    className: "bg-yellow-300 text-black",
    arweave: ["gTWFYybUFIU6AOVdmMeso0QRWLAskbTHRfq-t53Hb4k"],
  },
  {
    name: "Mastodon",
    icon: FaMastodon,
    className: "bg-indigo-900 text-white",
    arweave: ["Gh_-w2uwta_XppKzFqzNfKQwXMFj7kOp2Mx4JBxOUeI"],
  },
  {
    name: "Medium",
    icon: FaMedium,
    className: "bg-black text-white border-white border-2",
    arweave: ["SSZSfSVObB9erfJptLmaK7ozpuZ_EztE7VzwGoH6oOY"],
  },
  {
    name: "Microsoft",
    icon: FaMicrosoft,
    className: "bg-black text-white border-white border-2",
    arweave: ["dX2L9EEvqg2jwnG97Pf50wX3IwGel7ol5miE0iADHzU"],
  },
  {
    name: "Azure",
    icon: TbBrandAzure,
    className: "bg-white text-black border-2 border-black",
    arweave: ["wj3EwZf9myC_4rd3fLZQfauFEsN-FGvxsd0RvloymJA"],
  },
  {
    name: "Notion",
    icon: SiNotion,
    className: "bg-white text-black border-2 border-black",
    arweave: ["v_z1nuszV83h8MqWzCyfszX15yb5xN2dTg5QFmZPgTQ"],
  },
  {
    name: "Onlyfans",
    icon: SiOnlyfans,
    className: "bg-sky-500 text-white",
    arweave: ["URNnB5CRET52rFMcOFtD3Xs2IS7hNkdNU7JTBoN-PQk"],
  },
  {
    name: "Patreon",
    icon: FaPatreon,
    className: "bg-black border-2 border-white text-white",
    arweave: ["82zgZDdEW5x6fvseEyOC3FwzbFQnxFWeSxIxMhlE-gg"],
  },
  {
    name: "PayPal",
    icon: FaPaypal,
    className: "bg-blue-900 text-white",
    arweave: ["l2eRT5B5CBFcTGoxhDK0R3LHOf-39HYK6UavQ8UQLdU"],
  },
  {
    name: "Pinterest",
    icon: FaPinterest,
    className: "bg-white text-black border-2 border-black",
    arweave: ["zCyuFslkThSUO32PKtR5b5acOqISrxaAjRKSojA16m0"],
  },
  {
    name: "Product Hunt",
    icon: FaProductHunt,
    className: "bg-white text-black border-2 border-black",
    arweave: ["lrs_BMKJumWGib1Q61f_LOnfs_SlBpluFXgJvkE_UN0"],
  },
  {
    name: "Read.cv",
    icon: SiReaddotcv,
    className: "bg-black text-white border-2 border-white",
    arweave: ["uZSTzesctX_vJ0nR7M0ysfzDwshirIl7T7jtom6MkHY"],
  },
  {
    name: "Redbubble",
    icon: SiRedbubble,
    className: "bg-white text-black border-2 border-black",
    arweave: ["ES0Ns0QWGCME4GnnnVFDP8MjiN8sKrn20V0aPNRxTSY"],
  },
  {
    name: "Reddit",
    icon: FaReddit,
    className: "bg-orange-600 text-white",
    arweave: ["xsfj3JJ5gct3xAtEyuJbesTLsFBcwWr-GaQM6kQyQxs"],
  },
  {
    name: "Revolut",
    icon: SiRevolut,
    className: "bg-white text-black border-2 border-black",
    arweave: ["ScriYDPT7zXm8XetaUgMI0Z6BVjhdDZU9NkVLZBK4ps"],
  },
  {
    name: "Signal",
    icon: FaSignal,
    className: "bg-blue-500 text-white",
    arweave: ["4rJqESSdevyMWCPmIH0A-7W2aoY70NxFXo6TpWmBFR8"],
  },
  {
    name: "Slack",
    icon: FaSlack,
    className: "bg-white text-black border-2 border-black",
    arweave: ["fKEJ2iKOAQ-MNJcSNmiRAqC94ZNB_NDO923Ry6f-pjI"],
  },
  {
    name: "Snapchat",
    icon: FaSnapchat,
    className: "bg-yellow-300 text-black",
    arweave: ["kIPzD82kaSAJwn3PuOxr37bTO3V7qjez4CrDMBqL-IU"],
  },
  {
    name: "Spotify",
    icon: FaSpotify,
    className: "bg-green-500 text-black",
    arweave: ["7nO8y87KOcthl1jtsYncU5LAIyvzMsrA2MoUG_AUguA"],
  },
  {
    name: "Stackoverflow",
    icon: FaStackOverflow,
    className: "bg-white text-black border-2 border-black",
    arweave: ["f6FGVvBR16qQ19Gg7Qi_S2Jp9lmgN5VS1s1r9u4ayNE"],
  },
  {
    name: "Steam",
    icon: FaSteam,
    className: "bg-blue-500 text-white",
    arweave: ["KG_fe3yTFupIORzVKRO9rlO3IrNmiCSWnDi02g-ial8"],
  },
  {
    name: "Telegram",
    icon: FaTelegram,
    className: "bg-blue-400 text-white",
    arweave: ["R2fk_CuTSZWJCsGftDAywPKYQEfa78YpCTfyf-WWwwI"],
  },
  {
    name: "Threads",
    icon: FaThreads,
    className: "bg-black text-white border-2 border-white",
    arweave: ["e_HL-vbQC-bjaKh8MsZHJ0kgknbWWvLa3joxt7RzA3Y"],
  },
  {
    name: "TikTok",
    icon: FaTiktok,
    className: "bg-black text-white border-2 border-white",
    arweave: ["_kqqCivacAUruCaJW_Jg4mEvktjCYXS-jfkxMx7r56g"],
  },
  {
    name: "Trakt",
    icon: SiTrakt,
    className: "bg-red-700 text-white",
    arweave: ["-lipyJb0zDQEx3po3lS5V08KqvuJyOi5HP2CLubcxaE"],
  },
  {
    name: "Trello",
    icon: FaTrello,
    className: "bg-blue-600 text-white",
    arweave: ["WcjWZIYzwxk3nue1WtScicpShYKLom4nXvWbePe3Oz8"],
  },
  {
    name: "Tumblr",
    icon: FaTumblr,
    className: "bg-black text-white border-white border-2",
    arweave: ["ZcoAsQxZl4W5f3TD7B6sKfPvzt8qJDcWwdz5xDVhU6A"],
  },
  {
    name: "Twitch",
    icon: FaTwitch,
    className: "bg-purple-500 text-white",
    arweave: ["BasKHd1vj67S4niMrRJtF0v24efP7TZLXiS74cqLVK4"],
  },
  {
    name: "Unsplash",
    icon: FaUnsplash,
    className: "bg-white text-black border-2 border-black",
    arweave: ["5Hnai5TP-oFrqAcJXVu0XbwLOEA1_t75K6EiIIZp9pA"],
  },
  {
    name: "Upwork",
    icon: FaUpwork,
    className: "bg-green-600 text-white",
    arweave: ["imzlC3__TlrK27Px1hC3oDtif8P2Qo1nDt0Dt2wlFnA"],
  },
  {
    name: "Vimeo",
    icon: FaVimeo,
    className: "bg-cyan-500 text-white",
    arweave: ["5Z8mgl2ZqrTK-HeHfH-Eomo9_NaGIbwW7EuokR-ZsMQ"],
  },
  {
    name: "Whatsapp",
    icon: FaWhatsapp,
    className: "bg-gray-600  text-white",
    arweave: ["FhuVCRd9nSRLs3LxmNRhC-5QjxV1InZC3rKWzTpMNNI"],
  },
  {
    name: "Wordpress",
    icon: FaWordpress,
    className: "bg-blue-900 text-white",
    arweave: ["zXv3ZJ5N--6OWf8WflMROBCLuBpdX7mnQpqhfv5omkM"],
  },
  {
    name: "X",
    icon: FaXTwitter,
    className: "bg-black text-white border-white border-2",
    arweave: ["J_nEwmeE6oWwC1L9KV44Ez0m1GL-L9gTL6FbQwSnzm8"],
  },
  {
    name: "YouTube",
    icon: FaYoutube,
    className: "bg-black text-white border-white border-2",
    arweave: ["2ebs5GAw1558rpBCSwOguchAPMx91rOYzp4W-Eiliho"],
  },
  {
    name: "Zoom",
    icon: SiZoom,
    className: "bg-blue-600 text-white",
    arweave: ["Wce2AH-YQzGZpGhxQWSStzlYJbVuR_vRiukYX5NdZC8"],
  },
  {
    name: "Blog",
    icon: FaBlog,
    className: "bg-blue-600 text-white",
    arweave: ["hlmNprnVmyrKB8v9ONRKT3Avg4431Sv1v6EmhOOpq8M"],
  },
  {
    name: "Event",
    icon: FaCalendarAlt,
    className: "bg-blue-600 text-white",
    arweave: ["Qa8CPSj30BDlgANrs-c8UXsOP-xJwfys28zsO9IsEmk"],
  },
  {
    name: "Download",
    icon: FaDownload,
    className: "bg-blue-600 text-white",
    arweave: ["tVtK4Bt8Yw18Wdy2WiXZAR6EJgFT9Q7Lxb3sTlICml0"],
  },
  {
    name: "Code",
    icon: FaCode,
    className: "bg-blue-600 text-white",
    arweave: ["Y7USY85V5YX-AFetN8TcMUy-4JDRvVr-r-X6nLrNoys"],
  },
  {
    name: "Email",
    icon: FaEnvelope,
    className: "bg-blue-600 text-white",
    arweave: ["dYw_J9ywGFUMG7fOK6WwNCW3B2vguJp-WE8SNxVQUuE"],
  },
  {
    name: "Map",
    icon: FaMapMarkerAlt,
    className: "bg-blue-600 text-white",
    arweave: ["nb1EMboYyurWbGCg2veBzC-Zi_3hVXBfEsdm5fnaQ4w"],
  },
  {
    name: "Phone",
    icon: FaPhone,
    className: "bg-blue-600 text-white",
    arweave: ["4ZJnxCeSmtRYJqmdpX2Mo4ykT7-7vE3O0IkcNmuqXQI"],
  },
  {
    name: "Review",
    icon: FaCommentAlt,
    className: "bg-blue-600 text-white",
    arweave: ["3Xu5o1BIB-B8AgM6DxQcix8Fww4lfh0yMVqMDgOzjdk"],
  },
  {
    name: "Shopping",
    icon: FaShop,
    className: "bg-blue-600 text-white",
    arweave: ["BfQo7xUtywwClwJfOuRN-9DqLaODV4ZVN-wURxYIDJI"],
  },
  {
    name: "Message",
    icon: FaComment,
    className: "bg-blue-600 text-white",
    arweave: ["e2LpuqTDqWzN80oTJXCpxFf-6xs93BcEMmhRBjLXgPA"],
  },
  {
    name: "Web",
    icon: FaGlobe,
    className: "bg-blue-600 text-white",
    arweave: ["V3RlJd4MZ4rkNw9t_TVi68RF5nf9gIDHZ7RsHBJM-Fs"],
  },
];

export default AllLink;
